### PR TITLE
add new endpoint /maps ( https://wa.server.tld/maps )

### PR DESCRIPTION
**Pull request by Wikinaut**
+ to serve maps, tiles, assets like audio, video
  from the same server

### CODE REVIEW

**Comment by Wikinaut** [comment]
I tested this on my own server and confirm it working with maps, tiles and assets.

For the time being I decided to write and submit a distinct docker-compose file for this purpose.

**Comment by Wikinaut** [comment]
```
#     Defines a hardcoded /maps endpoint https://${BASE_DOMAIN}/maps
#     to serve your map files from local path /srv/maps/yourworld on your WA server.
#
#     Place your assets like audio and video files below that point.
#
#     Example for your WA start url:
#
#     https://${BASE_DOMAIN}/_/global/${BASE_DOMAIN}/maps/yourworld/main.json
#
#     Adapt endpoint "/maps" and local directory "/srv" (files are in /srv/maps)
#     according to your needs.
```

**Comment by rorist** [comment]
Hi,

I've just added a volume in the front for the time being xD

```
diff --git a/contrib/docker/docker-compose.prod.singledomain.yaml b/contrib/docker/docker-compose.prod.singledomain.yaml
index 42c924a..3f7edd6 100644
--- a/contrib/docker/docker-compose.prod.singledomain.yaml
+++ b/contrib/docker/docker-compose.prod.singledomain.yaml
@@ -49,6 +49,8 @@ services:
         TURN_SERVER: "$TURN_SERVER"
         TURN_USER: "$TURN_USER"
         MAX_PER_GROUP: "$MAX_PER_GROUP"
+    volumes:
+      - /srv/maps/fixme/:/usr/share/nginx/html/maps
     labels:
       - "traefik.http.routers.front.rule=PathPrefix(`/`)"
       - "traefik.http.routers.front.rule=Host(`${BASE_DOMAIN}`)"
```
Then `https://${BASE_DOMAIN}/_/global/${BASE_DOMAIN}/maps/main.json`, so just a bit shorter but only for one world.. It would be nice to have a smaller URL when serving from the same domain, like a shortcut.

**Comment by Wikinaut** [comment]
> Hi,
> 
> I've just added a volume in the front for the time being xD
> 
> ```
> diff --git a/contrib/docker/docker-compose.prod.singledomain.yaml b/contrib/docker/docker-compose.prod.singledomain.yaml
> index 42c924a..3f7edd6 100644
> --- a/contrib/docker/docker-compose.prod.singledomain.yaml
> +++ b/contrib/docker/docker-compose.prod.singledomain.yaml
> @@ -49,6 +49,8 @@ services:
>          TURN_SERVER: "$TURN_SERVER"
>          TURN_USER: "$TURN_USER"
>          MAX_PER_GROUP: "$MAX_PER_GROUP"
> +    volumes:
> +      - /srv/maps/fixme/:/usr/share/nginx/html/maps
>      labels:
>        - "traefik.http.routers.front.rule=PathPrefix(`/`)"
>        - "traefik.http.routers.front.rule=Host(`${BASE_DOMAIN}`)"
> ```
> 
> Then `https://${BASE_DOMAIN}/_/global/${BASE_DOMAIN}/maps/main.json`, so just a bit shorter but only for one world.. It would be nice to have a smaller URL when serving from the same domain, like a shortcut.

Can you please explain how (why?) the ```.../maps/fixme/``` part appears then to be served as ```.../maps/```, what/how is ```fixme``` substituted?

**Comment by rorist** [comment]
the map doesn't need to be in a subdirectory, you can have only one set of maps served at the root of the map server, in our case we have only one set of maps in maps (fixme is the repo for our map files https://git.fixme.ch/FIXME/rc3-world-fixme/).

**Comment by Wikinaut** [comment]
@rorist Sorry, and where and why is that defined ```/usr/share/nginx/html/maps``` ? I do not see any evidence in the docker-compose file for this this location, where is that stemming from?

**Comment by rorist** [comment]
@Wikinaut it's in the nginx config https://github.com/workadventure-xce/workadventure-xce/blob/xce/front/nginx-vhost.conf#L7 ;)

**Comment by pizkaz** [comment]
Not sure if this still works after latest changes on upstream (especially 3ef1f0dc7b326c3cf602c7fbeb5e638cf6fa13cc and following).
Also I don't like the idea of having too many `docker-compose.<whatchamacallit>.yml` files, because they all have to be fixed after breaking changes like the mentioned.

Right now, I believe, all compose files in `/contrib/docker` are broken for various reasons. :-(
We should focus on fixing those and maybe adding commented, commented-out sections instead of duplicating code and hence bugs.

**Comment by pizkaz** [comment]
I just fixed the docker-compose.yml for local development. :-)

**Comment by Wikinaut** [comment]
@rorist ```/usr/share/nginx/html/maps/xxx``` (but not! ```/srv/maps/fixme/xxx``` as explained in your post https://github.com/workadventure-xce/workadventure-xce/pull/11#issuecomment-810128019 ) is delivered as ```https://${BASE_DOMAIN}/maps/xxx``` .

What's wrong with my (or your code), please can you elaborate? If I get it working, I could delete my pull-request, as this would then fulfill my needs.

**Comment by pizkaz** [comment]
> @rorist `/usr/share/nginx/html/maps/xxx` (but not! `/srv/maps/fixme/xxx` as explained in your post [#11 (comment)](https://github.com/workadventure-xce/workadventure-xce/pull/11#issuecomment-810128019) ) is delivered as `https://${BASE_DOMAIN}/maps/xxx` .
> 
> What's wrong with my (or your code), please can you elaborate? If I get it working, I could delete my pull-request, as this would then fulfill my needs.

Assuming you added the exact two lines mentioned, it works exactly as expected:
The front container serves everything under `/usr/share/nginx/html`, so if you create a directory `maps/` in there, everything in there is served under `https://<fqdn>/maps/foobar`. When you map a folder on the host system to that directory (as is done with said two lines), files from that folder are served - in the provided example that is `/srv/maps/fixme`.

That is my understanding at least. ;-)

**Comment by Wikinaut** [comment]
> That is my understanding at least. ;-)

That was my understanding, too! But apparently it is not, and that's why I am asking.

**Comment by pizkaz** [comment]
Hmm do you see the files in question when you `docker-compose exec front sh` and `ls -l /usr/share/nginx/html/maps/`? Otherwise the bind mount of your volume is not working for some reason.

**Comment by Wikinaut** [comment]
oops. my fault!  I forgot the /html subdirectory!!! in that path . very sorry. Closing my pull request now, because the tiny fix in the "front" container is much better than to introduce "maps" again. 

Albrecht Dürer: Der Büßer (1510)
grafik

**Pull request closed without merging**
