### PR TITLE
Fixes the production single domain docker-compose file

### PR DESCRIPTION
**Pull request by justafish**
When starting this on a single domain the browser tries to access e.g. /pusher/anonymLogin instead of /anonymLogin

### CODE REVIEW

**Comment by pizkaz** [comment]
Thank you for your contribution! :-)

This is interesting. In my deployment I solved the problem the other way around, like it's done in the "official" [docker-compose.single-domain.yaml](https://github.com/workadventure-xce/workadventure-xce/blob/xce/docker-compose.single-domain.yaml): Configure Traefik to forward requests for `/pusher/<yada yada>` to the pusher container, stripping the `/pusher` part from the request URL.
I didn't get around to updating this compose file accordingly (the one I use is generated by Ansible).

I'm unsure which solution is cleaner. What do you think?

**Comment by justafish** [comment]
It's probably better to follow what the upstream composer file is doing - I just wasn't sure what all the other URLs listed in the traefik settings (e.g. /admin/rooms) were being used for so I didn't want to touch it :smile:

**Comment by tabascoeye** [comment]
_should_ be fixed by https://github.com/workadventure-xce/workadventure-xce/commit/d055088738601fac0c62715cce9878e4aa32ff45 as well.
Can you check?

**Comment by tabascoeye** [comment]
@justafish can you check if the current version works for you? I would like to close this issue

**Comment by justafish** [comment]
Just tested from the latest commit on the `xce` branch and it's working now - thanks!

**Pull request closed without merging**
